framgialink: "https://www.facebook.com/FramgiaVietnam"
khanhlink: "http://www.facebook.com/khanhmata.dn"
nguyenlink: "https://www.facebook.com/thaonguyen.tran.7311352"
rubyrailslink: "http://www.railstutorial.org/"
nothing: "#"
pagination:
  per_page: 10
  size: 10
remember_value: 1
user_per_page: 20
